# Graph-ND Start with Existing Database

In [1]:
import pandas as pd
from dotenv import load_dotenv
import os

from pydantic import BaseModel

load_dotenv('.env', override=True)

uri = "neo4j+s://demo.neo4jlabs.com"
username = "companies"
password = "companies"

In [9]:
import os

from graph_nd import GraphRAG, GraphSchema
from neo4j import GraphDatabase
from langchain_openai import OpenAIEmbeddings, ChatOpenAI

db_client = GraphDatabase.driver(uri, auth=(username, password))
llm = ChatOpenAI(model="gpt-4o", temperature=0.0)
embedding_model = OpenAIEmbeddings(model='text-embedding-ada-002')

In [10]:
db_client.execute_query('RETURN 1')

EagerResult(records=[<Record 1=1>], summary=<neo4j._work.summary.ResultSummary object at 0x145c4f490>, keys=['1'])

In [11]:
graphrag = GraphRAG(db_client, llm, embedding_model)

In [12]:
graphrag.schema.from_existing_graph()

INFO: Excluding node label '_Bloom_Scene_' due to exclusion rules.
INFO: Excluding node label '_Bloom_Perspective_' due to exclusion rules.

/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:137: UserWarning: No valid non-composite node constraints found on node `City`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:117: UserWarning: No valid property with range index found on node `City`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:137: UserWarning: No valid non-composite node constraints found on node `Country`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:117: UserWarning: No valid property with range index found on node `Country`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:137: UserWarning: No valid non-composite node constraints found on node `Chunk`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")

INFO: Excluding property `date` on node `Article` with type `DATE_TIME` as that type is unsupported.  Supported types include `{'BOOLEAN', 'DATE', 'INTEGER', 'FLOAT', 'DATETIME', 'STRING'}`

/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:117: UserWarning: No valid property with range index found on node `Chunk`. Choosing to use `text` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:137: UserWarning: No valid non-composite node constraints found on node `Fewshot`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/Users/zachblumenfeld/demo/graphrag-nd/graph_nd/graphrag/meta_queries.py:117: UserWarning: No valid property with range index found on node `Fewshot`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")

[Schema] Schema generated from existing graph

In [13]:
print(graphrag.schema.prompt_str())

{
    "description": "graph schema found in existing database",
    "nodes": [
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Person",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Organization",
            "properties": [
                {
                    "description": "",
                    "name": "isDissolved",
                    "type": "BOOLEAN"
                },
                {
                    "description": "",
                    "name": "nbrEmployees",
                    "type": "INTEGER"
                },
                {
                    "description": "",
                    "name": "revenue",
                    "type": "FLOAT"
                },
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "motto",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "isPublic",
                    "type": "BOOLEAN"
                },
                {
                    "description": "",
                    "name": "diffbotId",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "IndustryCategory",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "STRING"
            },
            "label": "City",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "STRING"
            },
            "label": "Country",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Article",
            "properties": [
                {
                    "description": "",
                    "name": "author",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "title",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "siteName",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "sentiment",
                    "type": "FLOAT"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "text",
                "type": "STRING"
            },
            "label": "Chunk",
            "properties": [],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "INTEGER"
            },
            "label": "Fewshot",
            "properties": [
                {
                    "description": "",
                    "name": "Question",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "Cypher",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        }
    ],
    "relationships": [
        {
            "description": "",
            "id": null,
            "type": "HAS_PARENT",
            "queryPatterns": [
                "(:Person)-[:HAS_PARENT]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CHILD",
            "queryPatterns": [
                "(:Person)-[:HAS_CHILD]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "IN_CITY",
            "queryPatterns": [
                "(:Organization)-[:IN_CITY]->(:City)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CEO",
            "queryPatterns": [
                "(:Organization)-[:HAS_CEO]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CATEGORY",
            "queryPatterns": [
                "(:Organization)-[:HAS_CATEGORY]->(:IndustryCategory)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_SUBSIDIARY",
            "queryPatterns": [
                "(:Organization)-[:HAS_SUBSIDIARY]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_SUPPLIER",
            "queryPatterns": [
                "(:Organization)-[:HAS_SUPPLIER]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_BOARD_MEMBER",
            "queryPatterns": [
                "(:Organization)-[:HAS_BOARD_MEMBER]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_COMPETITOR",
            "queryPatterns": [
                "(:Organization)-[:HAS_COMPETITOR]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_INVESTOR",
            "queryPatterns": [
                "(:Organization)-[:HAS_INVESTOR]->(:Person)",
                "(:Organization)-[:HAS_INVESTOR]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "IN_COUNTRY",
            "queryPatterns": [
                "(:City)-[:IN_COUNTRY]->(:Country)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CHUNK",
            "queryPatterns": [
                "(:Article)-[:HAS_CHUNK]->(:Chunk)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "MENTIONS",
            "queryPatterns": [
                "(:Article)-[:MENTIONS]->(:Organization)"
            ],
            "properties": []
        }
    ]
}

In [14]:
graphrag.agent("How many Companies are there?")

================================ Human Message =================================

How many Companies are there?
================================== Ai Message ==================================
Tool Calls:
  aggregate (call_qBdVPesjEF7Zl222YAe2CKe1)
 Call ID: call_qBdVPesjEF7Zl222YAe2CKe1
  Args:
    agg_instructions: Count the number of nodes with the label 'Organization'.
Running Query:
MATCH (o:Organization) RETURN count(o) AS numberOfOrganizations
================================= Tool Message =================================
Name: aggregate

[
    {
        "numberOfOrganizations": 46088
    }
]
================================== Ai Message ==================================

There are 46,088 companies in the database.

In [ ]:
graphrag.schema.from_existing_graph(text_embedding_fields=)

In [37]:
res_df = db_client.execute_query("""
SHOW INDEXES YIELD name, entityType, type, labelsOrTypes, properties, options
WHERE
  entityType="NODE"
  AND type IN ["FULLTEXT", "VECTOR"]
RETURN name AS indexName, type, labelsOrTypes AS labels, properties""",
                              result_transformer_ = lambda r: r.to_df())
res_df = (res_df
 .join(res_df['labels'].explode().rename('label'))
 .join(res_df['properties'].explode().rename('property')))
#res_df['multiLabel'] = res_df['labels'].map(len) > 1
#res_df['multiProperty'] = res_df['properties'].map(len) > 1
res_df

,indexName,type,labels,properties,label,property
0,entity,FULLTEXT,"[Person, Organization]",[name],Person,name
0,entity,FULLTEXT,"[Person, Organization]",[name],Organization,name
1,fewshot,VECTOR,[Fewshot],[embedding],Fewshot,embedding
2,news,VECTOR,[Chunk],[embedding],Chunk,embedding
3,news_fulltext,FULLTEXT,[Chunk],[text],Chunk,text
4,news_google,VECTOR,[Chunk],[embedding_google],Chunk,embedding_google
5,news_google_004,VECTOR,[Chunk],[embedding_google_004],Chunk,embedding_google_004

,indexName,type,labels,properties,label,property
0,entity,FULLTEXT,"[Person, Organization]",[name],Person,name
0,entity,FULLTEXT,"[Person, Organization]",[name],Organization,name
1,fewshot,VECTOR,[Fewshot],[embedding],Fewshot,embedding
2,news,VECTOR,[Chunk],[embedding],Chunk,embedding
3,news_fulltext,FULLTEXT,[Chunk],[text],Chunk,text
4,news_google,VECTOR,[Chunk],[embedding_google],Chunk,embedding_google
5,news_google_004,VECTOR,[Chunk],[embedding_google_004],Chunk,embedding_google_004

In [42]:
from graph_nd.graphrag.graph_schema import SearchFieldSchema
from typing import List
import warnings

def get_fulltext_search_fields(label:str, valid_properties:List[str], index_df) -> List[SearchFieldSchema]:
    # filter df to fulltext with label
    filtered_df = index_df[(index_df['type'] == 'FULLTEXT') & (index_df['label'] == label)].copy()
    #if filtered df has no rows return empty list
    if filtered_df.shape[0] == 0:
        return []
    #else more expensive checking
    result: List[SearchFieldSchema] = []
    for prop in valid_properties:
        prop_df = filtered_df[filtered_df['property'] == prop]
        if prop_df.shape[0] > 0:
            for ind, row in prop_df.iterrows():
                if len(row['labels']) > 1:
                    warnings.warn(f"WARNING: The fulltext index {row['indexName']} on labels {row['labels']} was encountered and will be ignored as fulltext indexes on multi-labels and multi-properties aren't supported yet.", UserWarning)
                elif len(row['properties']) > 1:
                    warnings.warn(f"WARNING: The fulltext index {row['indexName']} on properties {row['properties']} was encountered and will be ignored as fulltext indexes on multi-labels and multi-properties aren't supported yet.", UserWarning)
                else:
                    result.append(
                        SearchFieldSchema(
                            description='',
                            name=prop,
                            type="FULLTEXT",
                            calculatedFrom=prop,
                            indexName=row['indexName']
                        )
                    )
    return result

In [44]:
get_fulltext_search_fields('Chunk', ['text'], res_df)

[SearchFieldSchema(description='', name='text', type='FULLTEXT', calculatedFrom='text', indexName='news_fulltext')]

In [91]:
from typing import Dict
import pandas as pd


def check_vector_index_map( index_df:pd.DataFrame, index_map: Dict[str,str]):
    # we need to do some check ahead of time
    indices = index_df.loc[index_df['type'] == 'VECTOR', 'indexName'].unique()
    for ind, calc_prop in index_map.items():
        if ind not in indices:
            raise ValueError(f"The Vector index {ind} does not exist for any node properties in the database.")

def get_vector_search_fields(label:str, valid_properties:List[str], index_df:pd.DataFrame, index_map: Dict[str,str]) -> List[SearchFieldSchema]:
    # filter df to fulltext with label
    filtered_df = index_df[(index_df['type'] == 'VECTOR') &
                           (index_df['label'] == label) &
                           (index_df['indexName'].isin(index_map.keys()))].copy()
    #if filtered df has no rows return empty list
    if filtered_df.shape[0] == 0:
        return []
    #else more expensive checking
    result: List[SearchFieldSchema] = []
    for ind, calc_prop in index_map.items():
        ind_df = filtered_df[filtered_df['indexName'] == ind]
        if calc_prop in valid_properties:
            for i, row in ind_df.iterrows():
                if len(row['labels']) > 1:
                    warnings.warn(f"WARNING: The vector index {row['indexName']} on labels {row['labels']} was encountered and will be ignored as vector indexes on multi-labels and multi-properties aren't supported yet.", UserWarning)
                elif len(row['properties']) > 1:
                    warnings.warn(f"WARNING: The vector index {row['indexName']} on properties {row['properties']} was encountered and will be ignored as vector indexes on multi-labels and multi-properties aren't supported yet.", UserWarning)
                else:
                    result.append(
                        SearchFieldSchema(
                            description='',
                            name=row['property'],
                            type="TEXT_EMBEDDING",
                            calculatedFrom=calc_prop,
                            indexName=ind
                        )
                    )
    return result

def check_text_embedding_index_completeness(index_map: Dict[str,str], search_fields:List[SearchFieldSchema]):
    for ind, calc_prop in index_map.items():
        found = False
        for sf in search_fields:
            if sf.calculatedFrom == calc_prop and sf.indexName == ind and sf.type == "TEXT_EMBEDDING":
                found = True
                break
        if not found:
            raise ValueError(f"The text embedding field for `{{{ind}:{calc_prop}}}` was never found. This is likely due to the `{calc_prop}` not being of valid node property or associated with the same node label as the vector index named `{ind}`.")

In [92]:
tef = {'news':'text', 'news_google':'textual'}
check_vector_index_map(res_df, tef)

In [93]:
sfs = get_vector_search_fields('Chunk', ['text', 'name'], res_df, tef)
sfs

[SearchFieldSchema(description='', name='embedding', type='TEXT_EMBEDDING', calculatedFrom='text', indexName='news')]

In [94]:
check_text_embedding_index_completeness(tef, sfs)

ValueError: The text embedding field for `{news_google:textual}` was never found. This is likely due to the `textual` not being of valid node property or associated with the same node label as the vector index named `news_google`.

## GraphSchema Assumptions & Limitations

1. A GraphSchema is composed of three elements
    1. an optional description
    2. a list of NodeSchemas
    3. a list of relationshipSchemas
2. There can be only one node schema per node label and one relationship schema per relationship type.
3. Both nodes and relationships can have any number of properties
4. Only properties with types `ALLOWED_PROPERTY_TYPES = {"STRING", "INTEGER", "FLOAT", "BOOLEAN", "DATE", "DATETIME"}` can be considered
7. No methods in `graphrag.schema.*` assume any write permissions to the database (technically only [`reader`](https://neo4j.com/docs/operations-manual/current/authentication-authorization/built-in-roles/#access-control-built-in-roles-reader) permissions are assumed), meaning that no indexes or constraints can be set while creating schemas. They are instead checked and created if needed when writing data via `graphrag.data.*` methods. In general ONLY `graphrag.data.*` methods attempt writes and index/constraint setting.

### Node Schema Assumptions and Limitations
2. Every node label must have one id property (non-composite) which is assumed to uniquely identify nodes of that label.
    - This id property is required whenever loading nodes and relationships regardless of source (structured or unstructured)
    - in general elements (nodes and rels) are merged on unique id property(ies).
2. Vector and full text indexes are supported per node label through `searchFields` owned by the `NodeSchema`
3. Multi-label and multi-property vector/fulltext indexes are not currently supported. You can only use vector and full text indexes that are set on one node label and one node property.

### Relationship Schema Assumptions and Limitations
1.  Vector and full text indexes are not currently supported for relationship properties
2.  relationships have a list of one or more `queryPatterns`. A `queryPattern` is composed of a start and end node label.  The `queryPatterns` in a `RelationshipSchema` dictate which node labels a relationship can exist in between.
3. relationships have an *optional* id property which if provided is used to identify relationships for the purpose of maintaining parallel relationships (more than one instance of relationships of the same type existing between the same start and nodes).  If this id isn't provided repeat instances will be merged into the same single relationship when loading data.


## GraphSchema Opinions When Using `graphrag.schema.from_existing_graph`


### Naming Conventions & Exclusions
1. By default properties, labels and rel types leading with an underscore `_` or space ` ` are ignored.
    - Users can customize prefix, and exact match exclusion criteria across properties, labels, and relationships
    - `INFO` thrown on exclusion

### Node Label & Id
1. multi-labels are not considered.  If multi-labels are encountered they are treated as separate nodes.
2. node ids should have a non-composite uniqueness constraint on a property of `ALLOWED_PROPERTY_TYPES`. if multiple found then use `tie-break` logic. If non are found then the following fallback methods are tried in order.
     - `WARNING` must be thrown explaining fallback choices, not falling in `ALLOWED_PROPERTY_TYPES`, and tie breaking if it happens
     - fallback methods
       1. Look for properties with range indexes.  if found, choose the one with highest unique count. If ties, use `tie-break` logic
       2. Else find properties with highest unique count. If ties, use `tie-break` logic
       3. Else if no properties the node label must be ignored
     - `tie-break` logic: choose the shortest named property (i.e. between a property "id" and "name" - "id" would be chosen since it only has 2 chars vs 4). If same length choose first in ascending sort.

### Node Properties
1. properties which have a vector index will be excluded from property lists. This is to avoid them being returned to LLMs in retrieval and blowing context windows. They can be taken into account later with search fields which is a separate part of graph schema to inform vector search & retrieval
    - These are silently excluded
2. Only properties with types `ALLOWED_PROPERTY_TYPES` can be considered:
    - `WARNING` thrown on exclusion

### Relationship TYPE and Id
1. Only Relationship Types between included nodes (above) will be included
2. Relationship Ids (for parallel relationships) cannot be inferred and will be assumed None.  Users must provide an argument for relationship key(s)

### Relationship Properties
1. properties which have a vector index will be excluded from property lists. This is to avoid them being returned to LLMs in retrieval and blowing context windows.
     - These are silently excluded
2. Only properties with types `ALLOWED_PROPERTY_TYPES` can be considered:
    - `WARNING` thrown on exclusion

### Node Search Fields
1. Only FULLTEXT and TEXTEMBEDDING will be considered
2. for full text index it must be true that the property is included (from above) and the property has a full text index on it
3. For TEXTEMBEDDING this is more complicated because Neo4j does not associate the text embedding property to the field it was calculated from
    1. A user must specify the search field configuration.
    2. If the vector index corresponding isn't found an `ERROR` must be thrown

In [31]:
# get key uniqeness constrtaints
db_client.execute_query("""
SHOW CONSTRAINTS YIELD *
WHERE type IN ["NODE_KEY", "UNIQUENESS"] AND entityType="NODE"
RETURN labelsOrTypes[0] AS label, properties
""", result_transformer_= lambda r: r.data())

[{'label': 'Article', 'properties': ['id']},
 {'label': '_Bloom_Perspective_', 'properties': ['id']},
 {'label': 'IndustryCategory', 'properties': ['id']},
 {'label': 'Organization', 'properties': ['id']},
 {'label': 'Person', 'properties': ['id']}]

In [44]:

# get labels
db_client.execute_query("CALL db.labels()", result_transformer_= lambda r: r.value())

['_Bloom_Scene_',
 '_Bloom_Perspective_',
 'Person',
 'Organization',
 'IndustryCategory',
 'City',
 'Country',
 'Article',
 'Chunk',
 'Fewshot']

In [34]:
# get range indexes
db_client.execute_query("""
SHOW INDEXES YIELD *
WHERE type='RANGE' AND entityType='NODE'
RETURN labelsOrTypes[0] AS label, properties
""", result_transformer_= lambda r: r.data())

[{'label': 'Article', 'properties': ['id']},
 {'label': '_Bloom_Perspective_', 'properties': ['id']},
 {'label': 'IndustryCategory', 'properties': ['id']},
 {'label': 'Organization', 'properties': ['id']},
 {'label': 'Person', 'properties': ['id']}]

In [59]:
# get vector index properties
db_client.execute_query("""
SHOW INDEXES YIELD *
WHERE type='VECTOR' AND entityType='NODE'
RETURN labelsOrTypes AS labels, properties
""", result_transformer_= lambda r: r.data())

[{'labels': ['Fewshot'], 'properties': ['embedding']},
 {'labels': ['Chunk'], 'properties': ['embedding']},
 {'labels': ['Chunk'], 'properties': ['embedding_google']},
 {'labels': ['Chunk'], 'properties': ['embedding_google_004']}]

In [51]:
from typing import List


# count uniqueness
def count_distinct_node_props(label:str, properties:List[str]):
    counts = ', '.join([f'count(DISTINCT n.{p}) AS {p}' for p in properties])
    return  db_client.execute_query(f"""
            MATCH(n:{label})
            RETURN {counts}
            """, result_transformer_= lambda r: r.data()[0])

res = count_distinct_node_props("Person", ['name', 'id', 'summary'])
res

{'name': 7987, 'id': 8064, 'summary': 6401}

In [54]:
sorted(res, key=lambda x: (-res[x]))

['id', 'name', 'summary']

In [47]:
def get_properties_by_node_label():
    res = db_client.execute_query("""
    CALL apoc.meta.data()
    YIELD label, other, elementType, type, property
    WHERE NOT type = 'RELATIONSHIP' AND elementType = 'node'
    RETURN label AS nodeLabel, collect({name:property, type:type}) AS properties
    """, result_transformer_= lambda r: r.data())

    return {r['nodeLabel']: r['properties'] for r in res}


get_properties_by_node_label()

{'_Bloom_Scene_': [{'name': 'ranges', 'type': 'STRING'},
  {'name': 'gds', 'type': 'STRING'},
  {'name': 'createdAt', 'type': 'INTEGER'},
  {'name': 'lastModified', 'type': 'INTEGER'},
  {'name': 'style', 'type': 'STRING'},
  {'name': 'createdBy', 'type': 'STRING'},
  {'name': 'visualisation', 'type': 'STRING'},
  {'name': 'version', 'type': 'STRING'},
  {'name': 'roles', 'type': 'LIST'},
  {'name': 'numOfNodes', 'type': 'INTEGER'},
  {'name': 'numOfRels', 'type': 'INTEGER'},
  {'name': 'id', 'type': 'STRING'},
  {'name': 'relationships', 'type': 'STRING'},
  {'name': 'name', 'type': 'STRING'},
  {'name': 'nodes', 'type': 'STRING'}],
 '_Bloom_Perspective_': [{'name': 'data', 'type': 'STRING'},
  {'name': 'version', 'type': 'STRING'},
  {'name': 'roles', 'type': 'LIST'},
  {'name': 'name', 'type': 'STRING'},
  {'name': 'id', 'type': 'STRING'}],
 'Person': [{'name': 'name', 'type': 'STRING'},
  {'name': 'id', 'type': 'STRING'},
  {'name': 'summary', 'type': 'STRING'}],
 'Organization': [{'name': 'name', 'type': 'STRING'},
  {'name': 'nbrEmployees', 'type': 'INTEGER'},
  {'name': 'isDissolved', 'type': 'BOOLEAN'},
  {'name': 'id', 'type': 'STRING'},
  {'name': 'motto', 'type': 'STRING'},
  {'name': 'summary', 'type': 'STRING'},
  {'name': 'isPublic', 'type': 'BOOLEAN'},
  {'name': 'diffbotId', 'type': 'STRING'},
  {'name': 'revenue', 'type': 'FLOAT'}],
 'IndustryCategory': [{'name': 'name', 'type': 'STRING'},
  {'name': 'id', 'type': 'STRING'}],
 'City': [{'name': 'id', 'type': 'STRING'},
  {'name': 'summary', 'type': 'STRING'},
  {'name': 'name', 'type': 'STRING'}],
 'Country': [{'name': 'name', 'type': 'STRING'},
  {'name': 'id', 'type': 'STRING'},
  {'name': 'summary', 'type': 'STRING'}],
 'Article': [{'name': 'id', 'type': 'STRING'},
  {'name': 'author', 'type': 'STRING'},
  {'name': 'title', 'type': 'STRING'},
  {'name': 'siteName', 'type': 'STRING'},
  {'name': 'sentiment', 'type': 'FLOAT'},
  {'name': 'date', 'type': 'DATE_TIME'},
  {'name': 'summary', 'type': 'STRING'}],
 'Chunk': [{'name': 'text', 'type': 'STRING'},
  {'name': 'embedding', 'type': 'LIST'},
  {'name': 'embedding_google', 'type': 'LIST'},
  {'name': 'embedding_google_004', 'type': 'LIST'}],
 'Fewshot': [{'name': 'Question', 'type': 'STRING'},
  {'name': 'Cypher', 'type': 'STRING'},
  {'name': 'id', 'type': 'INTEGER'},
  {'name': 'embedding', 'type': 'LIST'}]}

In [73]:
def get_properties_by_rel_type():
    res = db_client.execute_query("""
    CALL apoc.meta.data()
    YIELD label, other, elementType, type, property
    WHERE NOT type = 'RELATIONSHIP' AND elementType = 'relationship'
    WITH label AS relType, collect({property:property, type:type}) AS properties
    RETURN relType, properties
    """, result_transformer_= lambda r: r.data())

    return {r['relType']: r['properties'] for r in res}


get_properties_by_rel_type()

{}

In [95]:
from typing import Dict, Optional, Tuple
import warnings
from graph_nd.graphrag.graph_schema import GraphSchema, NodeSchema, RelationshipSchema, PropertySchema, \
    NEO4J_PROPERTY_TYPES, QueryPattern, SearchFieldSchema  # assume imports for schema classes

# Helper functions
def is_excluded(name, exclude_prefixes, exclude_exact_matches):
    """Check if a name (label, property, or relationship type) should be excluded."""
    if any(name.startswith(prefix) for prefix in exclude_prefixes):
        return True
    if name in exclude_exact_matches:
        return True
    return False

def get_validated_node_properties(label, properties, exclude_prefixes, exclude_exact_matches, vector_properties) -> Dict[str, str]:
    validated_properties: Dict[str, str] = dict()
    for property in properties:
        if is_excluded(property['name'], exclude_prefixes, exclude_exact_matches):
            print(f"INFO: Excluding property `{property['name']}` on node `{label}` due to exclusion rules.")
        elif any(property['name'] in vp['properties'] and label in vp['labels'] for vp in vector_properties):
            continue
            #print(f"INFO: Excluding property `{property['name']}` on node `{label}` for the property schema since it is for a vector index. These properties are leveraged for vector search through search fields as specified by the user.")
        elif property['name'] in validated_properties:
            if property['type'] != validated_properties[property['name']]:
                warnings.warn(f"WARNING: Property `{property['name']} `on node `{label}` has conflicting types. found type `{property['type']}` but using `{validated_properties[property['name']]}` for schema.", UserWarning)
        elif property['type'] not in NEO4J_PROPERTY_TYPES:
            print(f"INFO: Excluding property `{property['name']}` on node `{label}` with type `{property['type']}` as that type is unsupported.  Supported types include `{NEO4J_PROPERTY_TYPES}`")
        else:
            validated_properties[property['name']] = property['type']
    return validated_properties

def get_validated_rel_properties(rel_type, properties, exclude_prefixes, exclude_exact_matches, vector_properties) -> Dict[str, str]:
    validated_properties: Dict[str, str] = dict()
    for property in properties:
        if is_excluded(property['name'], exclude_prefixes, exclude_exact_matches):
            print(f"INFO: Excluding property `{property['name']}` on relationship `{rel_type}` due to exclusion rules.")
        elif any(property['name'] in vp['properties'] and rel_type in vp['types'] for vp in vector_properties):
            continue
        elif property['name'] in validated_properties:
            if property['type'] != validated_properties[property['name']]:
                warnings.warn(f"WARNING: Property `{property['name']} `on relationship `{rel_type}` has conflicting types. found type `{property['type']}` but using `{validated_properties[property['name']]}` for schema.", UserWarning)
        elif property['type'] not in NEO4J_PROPERTY_TYPES:
            print(f"INFO: Excluding property `{property['name']}` on  relationship `{rel_type}` with type `{property['type']}` as that type is unsupported.  Supported types include `{NEO4J_PROPERTY_TYPES}`")
        else:
            validated_properties[property['name']] = property['type']
    return validated_properties


def break_tie_on_node_id_prop_candidates(label: str, id_candidates: List[str]) -> str:
    """
    Break ties among node ID property candidates based on highest count, shortest name,
    and alphabetical order (if needed).

    Parameters:
        label: The label for the node.
        id_candidates: List of candidate properties for determining the node ID.

    Returns:
        The best property name as the node ID.
    """
    # Step 1: Get counts for each candidate
    count_returns = ', '.join([f'count(DISTINCT n.{p}) AS {p}' for p in id_candidates])
    counts: Dict[str, int] = db_client.execute_query(f"""
            MATCH(n:{label})
            RETURN {count_returns}
            """, result_transformer_= lambda r: r.data()[0])
    # Step 2: Sort candidates by:
    #  - Descending count (-count sorts highest first)
    #  - Shortest length (len(x))
    #  - Alphabetical order (x)
    sorted_candidates = sorted(id_candidates, key=lambda x: (-counts[x], len(x), x))

    # Step 3: Return the first candidate (best match after sorting)
    return sorted_candidates[0]



def find_node_id_without_constraint(label: str, valid_property_candidates: List[str]) -> Tuple[str, str]:
    properties = db_client.execute_query(f"""
    SHOW INDEXES YIELD *
    WHERE type='RANGE' AND entityType='NODE' AND labelsOrTypes[0] = '{label}'
    RETURN properties
    """, result_transformer_= lambda r: r.value())
    valid_id_properties = []
    for prop in properties:
        if prop in valid_property_candidates:
            valid_id_properties.append(prop)

    if len(valid_id_properties) == 1:
        print(f"INFO: Choosing to use {valid_id_properties[0]} as the node id for node `{label}` as it has a range index.")
        return valid_id_properties[0], "indexed id property. Not guaranteed to be unique"
    elif len(valid_id_properties) > 1:
        res = break_tie_on_node_id_prop_candidates(label, valid_id_properties)
        warnings.warn(f"Multiple valid properties with range index found on node `{label}``: `{valid_id_properties}`. Choosing to use `{res}` as the node id.")
        return res, "indexed id property. Not guaranteed to be unique"
    else:
        res = break_tie_on_node_id_prop_candidates(label, valid_property_candidates)
        warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
        return res, "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance."


def find_node_id(label: str, label_constraints:List[Dict], valid_property_candidates: List[str]) -> Tuple[str, str]:

    label_constraint_candidates = []
    for label_constraint in label_constraints:
        if label_constraint['label'] == label:
            if len(label_constraint['properties']) > 1:
                warnings.warn(f"Composite constraint found for `{label_constraint['properties']}` on node `{label}`. It will be ignored as composite-constraints aren't supported.")
            else:
                label_constraint_candidates.append(label_constraint['properties'][0])
    if len(label_constraint_candidates) == 1:
        return label_constraint_candidates[0], "unique identifier"
    elif len(label_constraint_candidates) > 1:
        res = break_tie_on_node_id_prop_candidates(label, label_constraint_candidates)
        warnings.warn(f"Multiple valid non-composite node constraints found on node `{label}`: `{label_constraint_candidates}`. Choosing to use `{res}` as the node id.")
        return res, "unique identifier"
    else:
        warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
        return find_node_id_without_constraint(label, valid_property_candidates)



def create_node_schemas(
        exclude_prefixes=("_", " "),
        exclude_exact_matches=None,
        text_embedding_fields=None,
) -> List[NodeSchema]:

    # Initialize exclusion settings
    exclude_exact_matches = exclude_exact_matches or set()

    # get labels, properties and constraints
    labels = db_client.execute_query("CALL db.labels()", result_transformer_= lambda r: r.value())
    label_properties = get_properties_by_node_label()
    vector_properties = db_client.execute_query("""
                        SHOW INDEXES YIELD *
                        WHERE type='VECTOR' AND entityType='NODE'
                        RETURN labelsOrTypes AS labels, properties
                        """, result_transformer_= lambda r: r.data())
    label_constraints =  db_client.execute_query("""
                        SHOW CONSTRAINTS YIELD *
                        WHERE type IN ["NODE_KEY", "UNIQUENESS"] AND entityType="NODE"
                        RETURN labelsOrTypes[0] AS label, properties
                        """, result_transformer_=lambda r: r.data())
    node_list = []
    for label in labels:
        # Exclude the node if its label is excluded
        if is_excluded(label, exclude_prefixes, exclude_exact_matches):
            print(f"INFO: Excluding node label '{label}' due to exclusion rules.")
        # Exclude if no node properties
        elif label not in label_properties:
            warnings.warn(f"Excluding node label '{label}' due to no properties.", UserWarning)
        else:
            # get validated properties
            properties = get_validated_node_properties(label, label_properties[label], exclude_prefixes, exclude_exact_matches, vector_properties)
            # check for no valid properties and exclude if so
            if not properties:
                warnings.warn(f"Excluding node label '{label}' due to no properties with supported data types.", UserWarning)
            else:
                # get node id
                node_id, node_id_desc = find_node_id(label, label_constraints, list(properties.keys()))
                property_schemas = []
                node_id_schema = PropertySchema(description=node_id_desc, name=node_id, type=properties[node_id])
                # create property schema
                for prop_name, prop_type in properties.items():
                    if prop_name != node_id:
                        property_schemas.append(PropertySchema(name=prop_name, type=prop_type, description=""))
                # append node schema
                node_list.append(NodeSchema(id=node_id_schema, label=label, properties=property_schemas, searchFields=[], description=""))
    return node_list

In [96]:
def create_relationship_schemas(node_labels:List[str],
                                exclude_prefixes=("_", " "),
                                exclude_exact_matches=None,
                                parallel_rel_ids:Optional[Dict[str,str]]=None) -> List[RelationshipSchema]:

    if parallel_rel_ids is None:
        parallel_rel_ids = {}
    # Initialize exclusion settings
    exclude_exact_matches = exclude_exact_matches or set()

    # get rel_patterns & properties
    rel_patterns = db_client.execute_query("""
                    CALL apoc.meta.data()
                    YIELD label, other, elementType, type, property
                    WHERE type = 'RELATIONSHIP' AND elementType = 'node'
                    UNWIND other AS other_node
                    WITH *
                    RETURN {start: label, type: property, end: toString(other_node)} AS output
                    """, result_transformer_= lambda r: r.value())
    rel_properties = get_properties_by_rel_type()
    vector_properties = db_client.execute_query("""
                        SHOW INDEXES YIELD *
                        WHERE type='VECTOR' AND entityType='RELATIONSHIP'
                        RETURN labelsOrTypes AS types, properties
                        """, result_transformer_= lambda r: r.data())

    #consolidate relationship patterns under type
    rel_dict = dict()
    for rel_pattern in rel_patterns:
        # silently exclude the rel pattern if start or end are not in node_labels
        if (rel_pattern['start'] not in node_labels) or (rel_pattern['end'] not in node_labels):
            #print(f"INFO: Excluding relationship pattern `{rel_pattern}` due to start or end node not being in the provided node labels: `{node_labels}`.")
            continue
        elif rel_pattern['type'] in rel_dict:
            rel_dict[rel_pattern['type']].append(rel_pattern)
        else:
            rel_dict[rel_pattern['type']] = [rel_pattern]

    # logic by relationship type
    rel_schemas = []
    for rel_type, rel_patterns in rel_dict.items():
        # Exclude the rel pattern if type hits exclusion rule
        if is_excluded(rel_type, exclude_prefixes, exclude_exact_matches):
            print(f"INFO: Excluding relationship type `{rel_type}` due to exclusion rules.")
        else:
            # get valid properties
            if rel_type in rel_properties:
                properties = get_validated_rel_properties(rel_type, rel_properties[rel_type], exclude_prefixes, exclude_exact_matches, vector_properties)
            else:
                properties={}
            # get parallel rel id if available
            if rel_type in parallel_rel_ids:
                parallel_rel_id = parallel_rel_ids[rel_type]
                if not parallel_rel_id in properties:
                    raise ValueError(
                        f"The provided parallel id property `{parallel_rel_id}` for relationship type `{rel_type}` is missing or does not have a supported data type."
                    )
                else:
                    parallel_rel_id_schema = PropertySchema(name=parallel_rel_id, type=properties.pop(parallel_rel_id), description="")
            else:
                parallel_rel_id_schema = None
            # create property schema
            property_schemas = []
            for prop_name, prop_type in properties.items():
                property_schemas.append(PropertySchema(name=prop_name, type=prop_type, description=""))
            query_patterns = []
            for rel_pattern in rel_patterns:
                query_patterns.append(QueryPattern(startNode=rel_pattern['start'], endNode=rel_pattern['end'], description=''))
            rel_schemas.append(RelationshipSchema(type=rel_type, properties=property_schemas, queryPatterns=query_patterns, id=parallel_rel_id_schema, description=""))
    return rel_schemas



def create_graph_schema(exclude_prefixes=("_", " "),
                        exclude_exact_matches=None,
                        text_embedding_fields=None,
                        parallel_rel_ids:Optional[Dict[str,str]]=None,
                        description=None) -> GraphSchema:
    nodes = create_node_schemas(exclude_prefixes, exclude_exact_matches, text_embedding_fields)
    relationships = create_relationship_schemas([n.label for n in nodes], exclude_prefixes, exclude_exact_matches, parallel_rel_ids)
    return GraphSchema(nodes=nodes, relationships=relationships, description= description if description else "graph schema found in existing database")

In [97]:
res = create_graph_schema()

INFO: Excluding node label '_Bloom_Scene_' due to exclusion rules.
INFO: Excluding node label '_Bloom_Perspective_' due to exclusion rules.

/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:118: UserWarning: No valid non-composite node constraints found on node `City`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:98: UserWarning: No valid property with range index found on node `City`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:118: UserWarning: No valid non-composite node constraints found on node `Country`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:98: UserWarning: No valid property with range index found on node `Country`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:118: UserWarning: No valid non-composite node constraints found on node `Chunk`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")

INFO: Excluding property `date` on node `Article` with type `DATE_TIME` as that type is unsupported.  Supported types include `{'STRING', 'DATETIME', 'DATE', 'FLOAT', 'BOOLEAN', 'INTEGER'}`

/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:98: UserWarning: No valid property with range index found on node `Chunk`. Choosing to use `text` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:118: UserWarning: No valid non-composite node constraints found on node `Fewshot`. Falling back to range index lookup.
  warnings.warn(f"No valid non-composite node constraints found on node `{label}`. Falling back to range index lookup.")
/var/folders/dq/tkr53kq51wd04bk26m5s3_5c0000gn/T/ipykernel_52388/3627357328.py:98: UserWarning: No valid property with range index found on node `Fewshot`. Choosing to use `id` as the node id.
  warnings.warn(f"No valid property with range index found on node `{label}`. Choosing to use `{res}` as the node id.")

In [98]:
res.model_dump()

{'description': 'graph schema found in existing database',
 'nodes': [{'description': '',
   'id': {'description': 'unique identifier', 'name': 'id', 'type': 'STRING'},
   'label': 'Person',
   'properties': [{'description': '', 'name': 'name', 'type': 'STRING'},
    {'description': '', 'name': 'summary', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': 'unique identifier', 'name': 'id', 'type': 'STRING'},
   'label': 'Organization',
   'properties': [{'description': '', 'name': 'revenue', 'type': 'FLOAT'},
    {'description': '', 'name': 'name', 'type': 'STRING'},
    {'description': '', 'name': 'nbrEmployees', 'type': 'INTEGER'},
    {'description': '', 'name': 'isDissolved', 'type': 'BOOLEAN'},
    {'description': '', 'name': 'motto', 'type': 'STRING'},
    {'description': '', 'name': 'summary', 'type': 'STRING'},
    {'description': '', 'name': 'isPublic', 'type': 'BOOLEAN'},
    {'description': '', 'name': 'diffbotId', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': 'unique identifier', 'name': 'id', 'type': 'STRING'},
   'label': 'IndustryCategory',
   'properties': [{'description': '', 'name': 'name', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
    'name': 'id',
    'type': 'STRING'},
   'label': 'City',
   'properties': [{'description': '', 'name': 'summary', 'type': 'STRING'},
    {'description': '', 'name': 'name', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
    'name': 'id',
    'type': 'STRING'},
   'label': 'Country',
   'properties': [{'description': '', 'name': 'name', 'type': 'STRING'},
    {'description': '', 'name': 'summary', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': 'unique identifier', 'name': 'id', 'type': 'STRING'},
   'label': 'Article',
   'properties': [{'description': '', 'name': 'sentiment', 'type': 'FLOAT'},
    {'description': '', 'name': 'author', 'type': 'STRING'},
    {'description': '', 'name': 'siteName', 'type': 'STRING'},
    {'description': '', 'name': 'summary', 'type': 'STRING'},
    {'description': '', 'name': 'title', 'type': 'STRING'}],
   'searchFields': []},
  {'description': '',
   'id': {'description': "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
    'name': 'text',
    'type': 'STRING'},
   'label': 'Chunk',
   'properties': [],
   'searchFields': []},
  {'description': '',
   'id': {'description': "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
    'name': 'id',
    'type': 'INTEGER'},
   'label': 'Fewshot',
   'properties': [{'description': '', 'name': 'Question', 'type': 'STRING'},
    {'description': '', 'name': 'Cypher', 'type': 'STRING'}],
   'searchFields': []}],
 'relationships': [{'description': '',
   'id': None,
   'type': 'HAS_PARENT',
   'queryPatterns': [{'description': '',
     'startNode': 'Person',
     'endNode': 'Person'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_CHILD',
   'queryPatterns': [{'description': '',
     'startNode': 'Person',
     'endNode': 'Person'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_SUPPLIER',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Organization'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'IN_CITY',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'City'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_CATEGORY',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'IndustryCategory'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_CEO',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Person'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_SUBSIDIARY',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Organization'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_COMPETITOR',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Organization'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_BOARD_MEMBER',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Person'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_INVESTOR',
   'queryPatterns': [{'description': '',
     'startNode': 'Organization',
     'endNode': 'Person'},
    {'description': '',
     'startNode': 'Organization',
     'endNode': 'Organization'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'IN_COUNTRY',
   'queryPatterns': [{'description': '',
     'startNode': 'City',
     'endNode': 'Country'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'HAS_CHUNK',
   'queryPatterns': [{'description': '',
     'startNode': 'Article',
     'endNode': 'Chunk'}],
   'properties': []},
  {'description': '',
   'id': None,
   'type': 'MENTIONS',
   'queryPatterns': [{'description': '',
     'startNode': 'Article',
     'endNode': 'Organization'}],
   'properties': []}]}

In [100]:
print(res.prompt_str())

{
    "description": "graph schema found in existing database",
    "nodes": [
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Person",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Organization",
            "properties": [
                {
                    "description": "",
                    "name": "revenue",
                    "type": "FLOAT"
                },
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "nbrEmployees",
                    "type": "INTEGER"
                },
                {
                    "description": "",
                    "name": "isDissolved",
                    "type": "BOOLEAN"
                },
                {
                    "description": "",
                    "name": "motto",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "isPublic",
                    "type": "BOOLEAN"
                },
                {
                    "description": "",
                    "name": "diffbotId",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "IndustryCategory",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "STRING"
            },
            "label": "City",
            "properties": [
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "STRING"
            },
            "label": "Country",
            "properties": [
                {
                    "description": "",
                    "name": "name",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "unique identifier",
                "name": "id",
                "type": "STRING"
            },
            "label": "Article",
            "properties": [
                {
                    "description": "",
                    "name": "sentiment",
                    "type": "FLOAT"
                },
                {
                    "description": "",
                    "name": "author",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "siteName",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "summary",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "title",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "text",
                "type": "STRING"
            },
            "label": "Chunk",
            "properties": [],
            "searchFields": []
        },
        {
            "description": "",
            "id": {
                "description": "default id property. This node didn't seem to have a great id property so this was chosen by default. Not guaranteed to be unique and not indexed for fast query performance.",
                "name": "id",
                "type": "INTEGER"
            },
            "label": "Fewshot",
            "properties": [
                {
                    "description": "",
                    "name": "Question",
                    "type": "STRING"
                },
                {
                    "description": "",
                    "name": "Cypher",
                    "type": "STRING"
                }
            ],
            "searchFields": []
        }
    ],
    "relationships": [
        {
            "description": "",
            "id": null,
            "type": "HAS_PARENT",
            "queryPatterns": [
                "(:Person)-[:HAS_PARENT]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CHILD",
            "queryPatterns": [
                "(:Person)-[:HAS_CHILD]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_SUPPLIER",
            "queryPatterns": [
                "(:Organization)-[:HAS_SUPPLIER]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "IN_CITY",
            "queryPatterns": [
                "(:Organization)-[:IN_CITY]->(:City)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CATEGORY",
            "queryPatterns": [
                "(:Organization)-[:HAS_CATEGORY]->(:IndustryCategory)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CEO",
            "queryPatterns": [
                "(:Organization)-[:HAS_CEO]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_SUBSIDIARY",
            "queryPatterns": [
                "(:Organization)-[:HAS_SUBSIDIARY]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_COMPETITOR",
            "queryPatterns": [
                "(:Organization)-[:HAS_COMPETITOR]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_BOARD_MEMBER",
            "queryPatterns": [
                "(:Organization)-[:HAS_BOARD_MEMBER]->(:Person)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_INVESTOR",
            "queryPatterns": [
                "(:Organization)-[:HAS_INVESTOR]->(:Person)",
                "(:Organization)-[:HAS_INVESTOR]->(:Organization)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "IN_COUNTRY",
            "queryPatterns": [
                "(:City)-[:IN_COUNTRY]->(:Country)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "HAS_CHUNK",
            "queryPatterns": [
                "(:Article)-[:HAS_CHUNK]->(:Chunk)"
            ],
            "properties": []
        },
        {
            "description": "",
            "id": null,
            "type": "MENTIONS",
            "queryPatterns": [
                "(:Article)-[:MENTIONS]->(:Organization)"
            ],
            "properties": []
        }
    ]
}

### Add Additional Tools
...as many as you like

In [106]:
# get key uniqeness constrtaints
db_client.execute_query("""
SHOW INDEXES YIELD *
WHERE type IN ["RANGE"] AND entityType="NODE" AND "imdbId" IN properties
RETURN count(*) > 0 AS res
""", result_transformer_= lambda r: r.values()[0][0])

False